remote_theme: just-the-docs/just-the-docs@2ed4c0af735e95af5c0dcf7a605b07d903005b4e # v0.12.0

title: SSHScript v3.1 Documentation
description: Production documentation for SSHScript local and SSH automation
lang: en
repository: iapyeh/sshscript
url: "https://iapyeh.github.io"
baseurl: "/sshscript"
permalink: pretty

search_enabled: true
search:
  heading_level: 3
  previews: 3
heading_anchors: true
enable_copy_code_button: true
back_to_top: true
back_to_top_text: "Back to top"

aux_links:
  "GitHub":
    - "https://github.com/iapyeh/sshscript"
  "PyPI":
    - "https://pypi.org/project/sshscript/3.1.4/"
  "v3.1.4 Release":
    - "https://github.com/iapyeh/sshscript/releases/tag/v3.1.4"
aux_links_new_tab: true

gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/iapyeh/sshscript"
gh_edit_branch: "gh-pages"
gh_edit_view_mode: "edit"

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-include-cache

defaults:
  - scope:
      path: "v3a"
      type: "pages"
    values:
      layout: "default"
      nav_enabled: true

  - scope:
      path: "v1"
    values:
      nav_exclude: true
      search_exclude: true
  - scope:
      path: "v2"
    values:
      nav_exclude: true
      search_exclude: true
  - scope:
      path: "v3"
    values:
      nav_exclude: true
      search_exclude: true
