# This is auto generated by upload2pipy.spy
__version__ = "2.0.2"
try:
    from . import sshscript
    from . import sshscriptsession
    from . import sshscripterror
except ImportError:
    import sshscript
    import sshscriptsession
    import sshscripterror

runFile = sshscript.runFile
runScript = sshscript.runScript
SSHScriptSession = sshscriptsession.SSHScriptSession

setupLogger = sshscripterror.setupLogger
#setLogger = sshscripterror.setLogger
getLogger = sshscripterror.getLogger
SSHScriptError = sshscripterror.SSHScriptError

def run(script,_global=None,_local=None,showScript=False):
    if _global is None:
        _global ={'____sshscript____':[]}
    else:
        _global['____sshscript____']=[]
    script = script + '\n\n____sshscript____.append(($.stdout,$.stderr))'
    runScript(script,_global,_local,showScript)
    if showScript:
        return None,None
    else:
        return _global['____sshscript____'][0]

__all__ = ['run','runFile', 'runScript', 'SSHScriptSession','getLogger','setupLogger','SSHScriptError']