from typing import Any, ContextManager
from os import PathLike
from .session import Session as Session
from .commandresult import CommandResult as CommandResult
from .commandjob import CommandJob as CommandJob, JobResult as JobResult, CommandTimeoutError as CommandTimeoutError
from .errorutils import SSHScriptException as SSHScriptException

__version__: str

def check_file(script_path: str | PathLike[str]) -> int: ...
def run_file(script_path: str | PathLike[str], vars: dict[str, Any] | None = ..., showScript: bool = ...) -> int: ...
def run_script(script: str, varGlobals: dict[str, Any] | None = ..., showScript: bool = ...) -> dict[str, Any]: ...
def spy_imports() -> ContextManager[None]: ...
def get_logger() -> Any: ...
def set_logger(userlogger: Any = ..., logname: str | None = ...) -> Any: ...
