# This is auto generated by upload2pipy.spy
__version__ = "1.1.7"
from . import sshscript
runFile = sshscript.runFile
runScript = sshscript.runScript
SSHScript = sshscript.SSHScript
__all__ = ['runFile', 'runScript', 'SSHScript']