# This is auto generated by upload2pipy.spy
__version__ = "1.1.16"
try:
    from . import sshscript
    from . import sshscriptcore
    from . import sshscripterror
except ImportError:
    import sshscript
    import sshscriptcore
    import sshscripterror

runFile = sshscript.runFile
runScript = sshscript.runScript
SSHScript = sshscriptcore.SSHScript
setupLogger = sshscripterror.setupLogger
setLogger = sshscripterror.setLogger
getLogger = sshscripterror.getLogger
SSHScriptError = sshscripterror.SSHScriptError
SSHScriptCareful = sshscripterror.SSHScriptCareful

__all__ = ['runFile', 'runScript', 'SSHScript',
    'setLogger','getLogger','setupLogger',
    'SSHScriptError','SSHScriptCareful']