from dataclasses import dataclass
from types import TracebackType
from typing import Iterator
from .commandresult import CommandResult

@dataclass(frozen=True)
class JobResult(CommandResult[int | None]):
    stop_reason: str = ...
    termination_status: str = ...
    stdout_truncated: bool = ...
    stderr_truncated: bool = ...

class CommandTimeoutError(TimeoutError):
    result: JobResult
    command: str | tuple[str, ...]
    host: str | None
    timeout: float
    elapsed: float
    stdout: str
    stderr: str
    termination_status: str
    def __init__(self, result: JobResult, timeout: float) -> None: ...

class CommandJob:
    command: str | tuple[str, ...]
    host: str | None
    timeout: float | None
    stop_timeout: float
    capture_limit: int
    check: bool
    dropped_stdout_chunks: int
    @property
    def done(self) -> bool: ...
    @property
    def stdout(self) -> str: ...
    @property
    def stderr(self) -> str: ...
    @property
    def exitcode(self) -> int | None: ...
    def clear(self) -> None: ...
    def wait(self) -> JobResult: ...
    def stop(self) -> JobResult: ...
    def iter_stdout(self) -> Iterator[str]: ...
    def __enter__(self) -> CommandJob: ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool: ...
