from typing import Any

class SessionWrapper:
    @property
    def stdout(self) -> Any: ...
    @property
    def stderr(self) -> Any: ...
    @property
    def exitcode(self) -> int: ...
    @property
    def closed(self) -> bool: ...
    def set(self, *, check: bool = ..., verbose: bool = ..., verbose_stderr: bool = ..., log_level: int | str = ...) -> None: ...
    def get(self, name: str | None = ...) -> Any: ...
    def send_line(self, s: str, *, check: bool = ..., **expectations: Any) -> tuple[Any, Any] | str | None: ...
    __call__ = send_line
    exec_command = send_line
    def send(self, s: str) -> None: ...
    def input(self, s: str, timeout: float = ...) -> str | None: ...
    def expect(self, rawpat: Any, **kwargs: Any) -> Any: ...
