from typing import Any, ContextManager, Literal
from .commandresult import CommandResult

class SessionWrapper:
    @property
    def stdout(self) -> Any: ...
    @property
    def stderr(self) -> Any: ...
    @property
    def exitcode(self) -> int: ...
    @property
    def closed(self) -> bool: ...
    def set(self, *, check: bool = ..., verbose: bool = ..., verbose_stderr: bool = ..., log_level: int | str = ...) -> None: ...
    def get(self, name: str | None = ...) -> Any: ...
    def send_line(self, s: str, *, check: bool = ..., **expectations: Any) -> CommandResult[int] | str | None: ...
    __call__ = send_line
    exec_command = send_line
    def send(self, s: str) -> None: ...
    def input(self, s: str, timeout: float = ...) -> str | None: ...
    def expect(self, rawpat: Any, **kwargs: Any) -> Any: ...
    def su(self, username: str, password: str | None = ..., expect: Any = ..., initials: Any = ..., command: str | Literal[False] | None = ..., login: bool = ..., shell: Any = ..., get_pty: bool | None = ..., enter_timeout: float = ...) -> ContextManager[SessionWrapper]: ...
    def sudo(self, password: str | None = ..., username: str | None = ..., expect: Any = ..., initials: Any = ..., command: str | Literal[False] | None = ..., login: bool = ..., shell: Any = ..., get_pty: bool | None = ..., enter_timeout: float = ...) -> ContextManager[SessionWrapper]: ...
