from os import PathLike
from types import TracebackType
from typing import Any, ContextManager, Literal, TypedDict, overload
from .commandjob import CommandJob, CommandTimeoutError as CommandTimeoutError, JobResult
from .commandresult import CommandResult as CommandResult
from .sessionwrapper import SessionWrapper

Command = str | list[str] | tuple[str, ...]
class SessionSettings(TypedDict):
    check: bool
    verbose: bool
    verbose_stderr: bool
    log_level: int

class Session:
    closed: bool
    last_result: CommandResult[int] | JobResult | None
    close_errors: tuple[tuple[str, Exception], ...]
    logger: Any
    check: bool
    verbose: bool
    verbose_stderr: bool
    @property
    def log_level(self) -> int: ...
    @log_level.setter
    def log_level(self, value: int | str) -> None: ...
    def __init__(self, parent: Session | None = ...) -> None: ...
    def set(self, *, check: bool = ..., verbose: bool = ..., verbose_stderr: bool = ..., log_level: int | str = ...) -> None: ...
    @overload
    def get(self, name: None = ...) -> SessionSettings: ...
    @overload
    def get(self, name: Literal['check', 'verbose', 'verbose_stderr']) -> bool: ...
    @overload
    def get(self, name: Literal['log_level']) -> int: ...
    @overload
    def get(self, name: str) -> bool | int: ...
    @property
    def host(self) -> str | None: ...
    @property
    def connected(self) -> bool: ...
    @property
    def stdout(self) -> Any: ...
    @property
    def stderr(self) -> Any: ...
    @property
    def exitcode(self) -> int | None: ...
    @overload
    def exec_command(self, cmd: Command, *, shell: bool | str | None = ..., shell_executable: str | None = ..., check: bool = ..., command_timeout: float | None, **kw: Any) -> JobResult: ...
    @overload
    def exec_command(self, cmd: Command, *, shell: bool | str | None = ..., shell_executable: str | None = ..., check: bool = ..., **kw: Any) -> CommandResult[int]: ...
    __call__ = exec_command
    send_line = exec_command
    def start(self, cmd: Command, *, shell: bool | str | None = ..., shell_executable: str | None = ..., timeout: float | None = ..., stop_timeout: float = ..., capture_limit: int = ..., check: bool = ..., input: str | bytes | None = ..., env: dict[str, str] | None = ..., get_pty: bool = ...) -> CommandJob: ...
    def connect(self, host: str, username: str | None = ..., password: str | None = ..., port: int | None = ..., policy: Any = ..., *, ssh_config: str | PathLike[str] | bool | None = ..., **kw: Any) -> Session: ...
    @staticmethod
    def resolve_connection(host: str, **kwargs: Any) -> dict[str, Any]: ...
    def shell(self, command: str | None = ..., funcname: str = ..., get_pty: bool = ..., *args: Any, **kw: Any) -> ContextManager[SessionWrapper]: ...
    def enter(self, command: str, expect: Any = ..., password: str | None = ..., exit: str | None = ..., shell: bool = ..., get_pty: bool = ..., prompt: Any = ...) -> ContextManager[SessionWrapper]: ...
    def sudo(self, password: str | None = ..., username: str | None = ..., expect: Any = ..., initials: Any = ..., shell: bool = ..., login: bool = ..., get_pty: bool = ...) -> ContextManager[SessionWrapper]: ...
    def su(self, username: str, password: str | None = ..., expect: Any = ..., initials: Any = ..., shell: bool = ..., login: bool = ..., get_pty: bool = ...) -> ContextManager[SessionWrapper]: ...
    def upload(self, src: str | PathLike[str], dst: str, makedirs: bool = ..., overwrite: bool = ...) -> tuple[str, str]: ...
    def download(self, src: str, dst: str | PathLike[str] | None = ...) -> tuple[str, str]: ...
    def clear(self) -> None: ...
    def close(self, strict: bool = ...) -> bool: ...
    disconnect = close
    def __enter__(self) -> Session: ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool: ...
